//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingtipToys.SecretServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecretServiceReference.ISecretService")]
    public interface ISecretService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretService/DoWork", ReplyAction="http://tempuri.org/ISecretService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretService/DoWork", ReplyAction="http://tempuri.org/ISecretService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretService/GetSecretCode", ReplyAction="http://tempuri.org/ISecretService/GetSecretCodeResponse")]
        string GetSecretCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretService/GetSecretCode", ReplyAction="http://tempuri.org/ISecretService/GetSecretCodeResponse")]
        System.Threading.Tasks.Task<string> GetSecretCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretService/GetClientSecretCode", ReplyAction="http://tempuri.org/ISecretService/GetClientSecretCodeResponse")]
        System.Collections.Generic.KeyValuePair<string, int> GetClientSecretCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretService/GetClientSecretCode", ReplyAction="http://tempuri.org/ISecretService/GetClientSecretCodeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>> GetClientSecretCodeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecretServiceChannel : WingtipToys.SecretServiceReference.ISecretService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecretServiceClient : System.ServiceModel.ClientBase<WingtipToys.SecretServiceReference.ISecretService>, WingtipToys.SecretServiceReference.ISecretService {
        
        public SecretServiceClient() {
        }
        
        public SecretServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecretServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetSecretCode() {
            return base.Channel.GetSecretCode();
        }
        
        public System.Threading.Tasks.Task<string> GetSecretCodeAsync() {
            return base.Channel.GetSecretCodeAsync();
        }
        
        public System.Collections.Generic.KeyValuePair<string, int> GetClientSecretCode() {
            return base.Channel.GetClientSecretCode();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>> GetClientSecretCodeAsync() {
            return base.Channel.GetClientSecretCodeAsync();
        }
    }
}
